### ISSUE TITLE
RFE: allow to scroll box info (during character creation) using keyboard

### ISSUE THREAD

**Issue by VedVid** [thindil/steamsky#41]
Few moments ago I filed #38 because as a mostly keyboard oriented player I didn't notice that it's possible to scroll box info. It would be nice if I could do it using keyboard - maybe using keypad "+" and "-" or *normal* "-" "="? Or Page Up / Page Down?

**Comment by thindil** [comment]
Hello and ok, I will try to do it. I think Page Up/Page Down will be best option. Or maybe add option to set it, like others shortcuts? Just this may be overkill.

**Comment by VedVid** [comment]
Customizable in-game controls are always welcom, but I think it's normal that ui-related keys are fixed.

**Comment by thindil** [comment]
And this one is only partially fixed. Scrolling was worked earlier, just was very good hidden :) Now it works when you have selected any entry field (names of player or ship) too. Unfortunately, it still not works when you at selecting gender, faction or career. This is due to how that selection works (as it was mentioned in #42). If someone know better solution to this problem than current, please comment or reopen this issue or create new.
And as always: thank you very much again for report and I'm sorry for problems.
