### ISSUE TITLE
"Rhetoric: Legendary" + "Talking in bases" = crash

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#60]
I hired a crew member with Rhetoric: Legendary (I guess: Only one notch from Ultimate.)
And when "Talking in bases" the game crashes when entering a location where that is relevant.

error.log say:

Message: ships-crew.adb:66 range check failed

**Comment by thindil** [comment]
And thank you again for the report and I'm sorry for the problems.

Of course, I will try to fix it tomorrow too, same as earlier bug ;)

**Comment by thindil** [comment]
Ok, this should be fixed now, again, thank you very much for the report :)

**Comment by Lars-Dahl** [comment]
Slightly different, but still not fixed properly:

[error.log](https://github.com/thindil/steamsky/files/4334655/error.log)

**Comment by thindil** [comment]
Ok, I will try to fix it, but this time, it will take around 2 weeks before fix will be released. It looks similar but it is not this same problem ;)

**Comment by thindil** [comment]
Ok, lets see if it will be fixed this time ;) Just as I wrote ealier, official release will be in around 2 weeks. At this moment, here is not too easy way to check it with testing version of the game: https://github.com/thindil/steamsky/tree/4.0#testing-versions

Thank you again for the report.
